### ISSUE TITLE
Congratulations!

### ISSUE THREAD

**Issue by ManuLintz** [sinclairzx81/smoke#1]
Hi,

I saw your post on r/WebRTC, and I just wanted to tell you that this library seems pretty awesome!
Even if don't understand what smoke exactly does, I really like the idea of running services in the browser for WebRTC.

Also, the Readme looks really good :)

**Comment by sinclairzx81** [comment]
Hi, Thanks, Glad you like it :)

I've just published some generated documentation for the project to provide a bit more insight into some of the codebases internals. If you have any specific questions with regards to how various parts of the codebase works, ill be happy to answer them (and perhaps draft a FAQ if the project gains some interest in future).

Generated Docs are [here](https://sinclairzx81.github.io/smoke/index.html)

Thanks Again !
