### ISSUE TITLE
MIA

### ISSUE THREAD

**Issue by Cinemacloud** [sinclairzx81/smoke#10]
Hey mate can't seem to get you via irc or email, still want to do smoke dev together?

**Comment by sinclairzx81** [comment]
Hey mate, Have been fairly busy on contracts and other work of late. Would be keen to do some dev, but won't be able to dedicate much time to it for a good few months. I'll be back once I've wrapped up on other work.

Cheers mate.

**Comment by Cinemacloud** [comment]
Roger, hit my email when ready

**Comment by Cinemacloud** [comment]
Hey are you ignoring me? what's up. Sorry for whatever caused you to do this, I tjink I know why. You are welcome to make amends and we can reconvene on irc.
