### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by ansarizafar** [sinclairzx81/smoke#11]
Smoke is an amazing project but there is not activity is the public repository. What is the status of this project? Is it dead?

**Comment by sinclairzx81** [comment]
@ansarizafar Hi. This project is not dead, but it has been in a rather lengthy pending state while I've waited on a few web specifications to iron themselves out (and for a time I've been a bit less busy with other work). I will be returning to development on smoke at some point, possibly under a new name (leaving smoke as a working prototype name), with API's less aligned with node, and more with emerging browser API.

Hopefully that provides a little bit of insight into the state of the library. Thanks for the interest!
S

**Comment by ansarizafar** [comment]
Thanks for the update.

**Comment by zababurinsv** [comment]
> @ansarizafar Hi. This project is not dead, but it has been in a rather lengthy pending state while I've waited on a few web specifications to iron themselves out (and for a time I've been a bit less busy with other work). I will be returning to development on smoke at some point, possibly under a new name (leaving smoke as a working prototype name), with API's less aligned with node, and more with emerging browser API.
> 
> Hopefully that provides a little bit of insight into the state of the library. Thanks for the interest! S

Hi! It is great project.
Will I be able to use your project now to process requests on the client side?

**Comment by ansarizafar** [comment]
Hopping for a new release this year.

**Comment by sinclairzx81** [comment]
@ansarizafar Just released a new version of this project (which is a complete rebuild). Most of the existing functionality has been retained, however the API's have been modernized inline with modern WHATWG JavaScript network primitives.

Currently the project only supports localhost connections, but will be updating the new Public hub along with a reference WebSocket server implementation at a later time.

Latest version can be installed with

```bash
$ npm install @sinclair/smoke
```
Will close off this issue for now.
S

**Comment by unao** [comment]
@sinclairzx81 the project looks amazin
g.
Do you need any help with the Public Hub? Could you briefly sketch what would be involved to move forward with the Public Hub?

**Comment by sinclairzx81** [comment]
@ansarizafar Hi, thanks :)

> Do you need any help with the Public Hub? Could you briefly sketch what would be involved to move forward with the Public Hub?

The Public Hub is mostly an abstract concept involving a WebSocket server and client implementation, so there isn't too much to move forward with, aside from standardizing a set of protocols that web servers should implement to support the Hub’s role (in a more formal sense). If a Public Hub implementation gets written, it would need to adhere to that protocol, but I still need to work out some finer details. It might not happen, as there are many ways to implement a Public Hub using a variety of methods / protocols, all of which would be equally valid. We’ll see.

However, if you're interested, I've set up a defacto reference project that implements a current version of the Public Hub using the [Sidewinder](https://github.com/sinclairzx81/sidewinder) project. This project also encodes structures documenting interactions between the client and server, and it includes a client Hub implementation.

You can find the reference project at the link below:

---

[smoke-setup.zip](https://github.com/user-attachments/files/16478107/smoke-setup.zip)

Instructions:

- Extract `smoke-setup.zip` somewhere
- Navigate to project root and run `npm install` (installs typescript, smoke, sidewinder)
- Use `npm start` to start
- Visit `http://localhost:5000` and view console logs

---

In terms of contributing to the project, setting up the reference project and experimenting with building different types of applications over a peer network would be incredibly helpful. Any information or feedback you can provide—whether it's feature requests, bug reports, or even publishing implementations of the library—would help steer the project forward. I'm a big advocate for guiding features through real usage, so any info you can provide would be a huge help

Cheers!
S

**Comment by unao** [comment]
Thank you. I was easily able to run it. I will take a closer look (probably after the weekend). 

Btw. `sidewinder` is **really** cool.
