### ISSUE TITLE
Does it run on the browser? How to?

### ISSUE THREAD

**Issue by pbeltranl** [sinclairzx81/smoke#12]
Hi,

I've built _smoke_ with _browserify_ to run it on the browser (latest version of Chrome). This part seems ok since all the objects are created with no errors.

However, after the _app.listen(9999)_ instruction nothing happens. No TCP port opened. No log traces either anywhere.

Below is the example used for testing this:

#>>>>>>>>>>>>>>>
 var _smokeNode = require("smoke-node");

  const host = new  _smokeNode.Node();

  const app = host.rest.createServer()

  app.get('/', async (req, res) => {

    res.headers['Content-Type'] = 'text/html'
    
    res.send("<h1>hello world</h1>");
  })

  app.listen(9999)
<<<<<<<<<<<<<<<<<<

What are the recommended steps to run it on the browser?

Thanks,
Pablo

**Comment by shynome** [comment]
change the client port
```js
const resp = await node.rest.fetch(`rest://${await host.address()}:9999/`).then((r) => r.text());
```

**Comment by szcuipeng** [comment]
may i ask a question? how to build smoke with browserify?

**Comment by Terence39** [comment]
Wooo that is naaaa

**Comment by sinclairzx81** [comment]
@Terence39 Heya,

This code does run in the browser, but I wouldn't use this incarnation of this project for any serious work (this project was a prototype for something far more significant)

So, despite the years that have elapsed, I haven't forgotten about this project, and given there's still some interest in it, I do plan to publish a major update taking advantage of modern browser capabilities that weren't present when this project was originally written.

Stay tuned

**Comment by sinclairzx81** [comment]
Hiya,

Going to close this issue off as it's stale. This project has been overhauled and can now be installed via.

```bash
$ npm install @sinclair/smoke
```
It should run in Chrome and Firefox. Safari support may be hit or miss however.
Cheers
S
