### ISSUE TITLE
heartbeat, switch from wifi to 4G/5G, connect use fixed address with password ...

### ISSUE THREAD

**Issue by szcuipeng** [sinclairzx81/smoke#16]
i need some new features:

(1) heartbeat between socket client and server
(2) when my phone's network switch from wifi to 4G/5G, socket shoud reconnect and keep session
https://stackoverflow.com/questions/41098670/how-to-gracefully-switch-between-networks-in-webrtc

(3) i found that Dhcp will increase address number,  sometimes some nodes need connect to a server with fixed address, so a server should be use fixed address ( the server will connect to network-hub with a fixed address )

i found it:
https://github.com/sinclairzx81/smoke/issues/8

(4) smoke-hub cluster

**Comment by sinclairzx81** [comment]
@szcuipeng Hi,

Going to close off this issue as it's largely stale. The project has just undergone a rebuild with the Dhcp component removed in favor of unique identifiers (although implementations can still create the IPv4 looking addresses through Hub implementations)

New version can be installed with

```bash
$ npm install @sinclair/smoke
```
Usage documentation can be found in the readme.
Cheers!
S
