### ISSUE TITLE
Cause for firefox not being supported: RTCDataChannel.binaryType deafults to "blob"

### ISSUE THREAD

**Issue by minwidth0px** [sinclairzx81/smoke#24]
I looked into the issue of Firefox not working, and the issue appears to be that the default value for [RTCDataChannel.binaryType](https://developer.mozilla.org/en-US/docs/Web/API/RTCDataChannel/binaryType)  on Firefox is `"blob"` and on Chrome and Webkit it's `"arraybuffer"`. Originally, the spec's default value was `"blob"`, but chrome never respected that, and the default value was actually changed to `"arraybuffer"` in January of this year (see https://github.com/w3c/webrtc-pc/issues/2170), but Firefox has not implemented that yet. Interestingly, chrome started supporting "blob" as of last week (see https://issues.webrtc.org/issues/41480941). What is more, setting `datachannel.binaryType = "arraybuffer"` in `WebRtcModule.connect` alone does not solve it. The  `RTCDataChannel` when logged shows that it is of binaryType `"arraybuffer"`, but when printing the following in `NetSocket.connect` you can see that the messages being sent are still of type `"blob"`:

```js

  #onMessage(event) {
    console.log(event.data)
    if(event.data instanceof Blob) {
      console.log("Blob detected")
      event.data.arrayBuffer().then(buffer => {
        console.log("decoded text: ", new TextDecoder().decode(new Uint8Array(buffer)));
      });
    }
    console.log(new TextDecoder().decode(new Uint8Array(event.data)));
    this.#readchannel.send(new Uint8Array(event.data));
  }

```

Firefox:

```

Blob { size: 47, type: "" }
Blob detected
<empty string>
decoded text:  �������'{"headers":{},"method":"GET","url":"/"}

```

Chrome:

```

byteLength: 47detached: falsemaxByteLength: 47resizable: false[[Prototype]]: ArrayBuffer[[Int8Array]]: Int8Array(47)[[Uint8Array]]: Uint8Array(47)[[ArrayBufferByteLength]]: 47[[ArrayBufferData]]: 1509
'{"headers":{},"method":"GET","url":"/"}

```

I plan to investigate the root cause of this issue and maybe file a PR. For now, the following fixes the issue and allows Smoke to work on Firefox:

```js

  #onMessage(event) {
    if(event.data instanceof Blob) {
      event.data.arrayBuffer().then(buffer => {
        this.#readchannel.send(new Uint8Array(buffer));
      });
    }else{
      this.#readchannel.send(new Uint8Array(event.data));
    }
  }

```

Looks like https://bugzilla.mozilla.org/show_bug.cgi?id=1245138 might be related here:

>If you want to receive data as an arraybuffer, you must set it to arraybuffer on the receiver side

Although it is set on the receiver's side as well in this case...

**Comment by sinclairzx81** [comment]
@minwidth0px Hi! 

Thank you for taking the time to look into this! This is great. I will look into this later today and see if I can apply a fix. I have had difficulties with Firefox over the past few years (WebRTC has been a moving target), but it is still reasonable to try and support them if the disparities are down to configurations and/or the updates do not implicate performance using a common code path.

Will do some digging :)

**Comment by sinclairzx81** [comment]
@minwidth0px Hiya, 

So, the update was fairly straight forward, just a case of setting the `binaryType` on the DataChannel enables Firefox to connect on loopback and return a response (the project example should run ok)

https://github.com/sinclairzx81/smoke/blob/master/src/net/socket.mts#L48

Sadly running the test suite against Firefox has some notable issues, mostly related to concurrency and parallel connections (which may be either signaling / RTCPeerConnection related, or buffering related, I'm not sure). Unfortunately I don't have testing infrastructure setup to run both Chrome and Firefox, but you can run the Firefox test by adding the following to `example/index.mts`

```typescript
import '../test/index.mjs'
```
And editing the following in `test/index.mts`

```typescript
declare const Drift: any
Test.run({ filter: '' /* Drift.args[0] */ }).then((result) => { // remove Drift from filter
  return result.success ? Drift.close(0) : Drift.close(1)
})
```

Then just run in the browser on `http://locahost:5000`

---
### Some Thoughts 

Smoke implements quite a lot of concurrency / congestion buffering control over RTCDataChannels in Chrome. Most documentation suggests that a RTCDataChannel has a 32K/64K send buffer, however Chrome appears to share that buffer across multiple channels on the same RTCPeerConnection (meaning 32/64K buffer is per Connection (not per Channel)), at least this is what I've found to be true through a fair amount of experimentation (I've not looked at actual WebRTC implementation). The following is code relates to this:

https://github.com/sinclairzx81/smoke/blob/master/src/net/socket.mts#L101-L134

It's highly probable that Firefox has a completely different implementation, meaning congestion control algorithms developed for Chrome may not be suitable in Firefox (or only be partially workable). But I'm guessing here.

Historically I've had problems with Firefox in the past related to concurrency, of which implementations required quite a lot over buffering overhead and performance degradation trying to support the transport characteristics of both WebRTC implementations. Unfortunately, I can't remember all the details there so it would require experimentation and research to land on a good implementation (ideally one that wouldn't degrade the current Chrome implementation)

I am open to collaboration and research on some of these finer details, and certainly would like to work closer with the community more to help push this project forward (these are hard problems to solve). If you are able to offer any research into some of this, it would help get Firefox better implemented in the library (and any and all insights would lead to better implementations). 

Will close of this issue for now, but happy to continue to discuss things more if you are interested.

Cheers
S

**Comment by minwidth0px** [comment]
@sinclairzx81 Thanks for pushing a fix so quickly!

>So, the update was fairly straight forward, just a case of setting the binaryType on the DataChannel enables Firefox to connect on loopback and return a response 

Ah, I only searched for `createDataChannel` as I though that was the only way to create a DataChannel, so I only tried setting `datachannel.binaryType = "arraybuffer"` in `WebRtcModule`.  Glad to see the issue was resolved though.

>If you are able to offer any research into some of this, it would help get Firefox better implemented in the library (and any and all insights would lead to better implementations).

I can definitely try, although it was more luck that I even found the source of this bug by just stepping into the fetch method with the debugger and looking for differences in the local scope between Firefox and Chrome. If I run into more issues with Firefox I can definitely try to do the same to solve them, although right now I'm mainly working on #22 and trying to get [Webtorrent trackers](https://github.com/webtorrent/bittorrent-tracker) to work as a signaling server. Right now it works for some trackers but not all (see my issue in that repo if you are interested, or my WebtorrentHub class [https://github.com/minwidth0px/Webrtc-NAT-Traversal-Proxy-Server/blob/main/src/client/hubs/webtorrentHub.mts](here)).

**Comment by sinclairzx81** [comment]
@minwidth0px Hi, I've done some digging into Firefox connectivity issues and wanted to follow up on this.

I traced the problem to an intermittent issue in Firefox where the `RTCPeerConnection` `datachannel` event isn't always emitted, even though the client-side `RTCDataChannel` does emit an `open` event. Below are the logs from running the (sequential x 64) test from the suite:

```
 - Should listen fetch then close (sequential x 64) index.js:671:60
0 
webtrc: client datachannel open
webtrc: server ondatachannel event <--- ok
http: server on request
fetch: sent request init
http: read request init
fetch: read protocol signal
read response init 
webtrc: client datachannel close
1 
webtrc: client datachannel open
webtrc: server ondatachannel event <--- ok
http: server on request
fetch: sent request init
http: read request init
fetch: read protocol signal
read response init
webtrc: client datachannel close 
2 
webtrc: client datachannel open 
webtrc: server ondatachannel event <--- ok
http: server on reques
fetch: sent request init
http: read request init 
fetch: read protocol signal
read response init
webtrc: client datachannel close 
3 
webtrc: client datachannel open
fetch: sent request init <--- client datachannel opened, peer connection did not
```
This issue causes the client data channel to open, assuming the transport is ready to send data. The client then starts transmitting protocol messages and waits for a response from the server. However, since the server never received a datachannel event, the client ends up hanging.

It would be worth checking if there are any open issues related to "PeerConnection datachannel event not emitting" or similar in the Firefox bug trackers.

---

I've encountered similar inconsistencies with Firefox in the past, making it challenging to support. While I could add a timeout on the fetch side to trigger a "Transport Error" or something similar, I'm hesitant to add too much browser-specific compensation code. I've been down this path before in other projects, and it often results in code that's cluttered with workarounds, which can impact maintainability.

I'll do investigations on the protocol message timeout (on fetch) and see if that enables the RTCPeerConnection to resume on a new RTCDataChannel connection attempt. If I recall, there have been cases where the RTCPeerConnnection on both sides can get into an inconsistent state meaning no more connections can be established (requiring a full connection tear down on both sides). If the above issue is a symptom of such inconsistencies, there's isn't much Smoke can do patch over this, and would need to submit to Firefox issue trackers.

Will keep you posted

**Comment by sinclairzx81** [comment]
@minwidth0px Hiya,

So, have carried out some addition tests. And it does look as though once Firefox peer connections go awol, they cannot be resumed (and I don't have a good way to catch for these cases in smoke as it's a Firefox bug, and Firefox gives no hints other than things just stop working). 

This said, I've submitted an update to handle protocol message timeout (on fetch) and added a hub message to handle peer connection termination at both local and remote sides. You can read about the updates and code at the following PR

https://github.com/sinclairzx81/smoke/pull/26

It's not ideal, but should work around the issue in Firefox. I've managed to get most the test suite passing here by catching and terminating connections on error (albiet the fetches do fail), but subsequent requests can succeed on different connections made after the previous connections are terminated.

If you end up using this, would be keen to get some insight into how things go. 
Cheers
S

**Comment by minwidth0px** [comment]
@sinclairzx81 I haven't read the entirety of your post yet, as I actually came here to open a PR for Firefox. Basically, at least one issue is that  `datachannel.binaryType = "arraybuffer";` must be set in `connect` in `webrtc.mjs` as well. Here is a somewhat stripped down example that shows this. It still requires some functions from https://github.com/minwidth0px/Webrtc-NAT-Traversal-Proxy-Server to work. (I can make it even more minimal if necessary)

```html

<!doctype html>
<html>

<head>
<title>test</title>
</head>
<body>
    <div>
        <div> <input placeholder="URL" id="base-url"/> </div>
        <div> <input placeholder="Key" id="api-key"/> </div>
        <button id="start" class="button-4">Start</button>
    </div>
    <script type="module">

		import networkService from './networkService.js'
		
        document.getElementById("start").addEventListener("click", () => {
            connect()
        })
		async function connect(){
			const urlObj = new URL(document.getElementById("base-url").value)
			const searchParams = urlObj.searchParams
			const useSmoke = true
			let ws = null
			const infoHash = searchParams.has("infoHash")? searchParams.get("infoHash") : ""
            const wsUrl = 'wss://tracker.files.fm:7073'  
            ws = new WebSocket(wsUrl)
            const peerId = window.crypto.randomUUID().replaceAll('-', '').slice(0, 20)
            networkService.setNetwork(ws, infoHash, peerId, urlObj.origin)
			ws.addEventListener('open', async () => {
                const text = await networkService.smokeClient.Http.fetch([networkService.remoteAddr, "test"].join("/")).then(r => r.text());
                console.log(text);
                console.log("ws open")
            })
		}
   </script>
</body>

</html>

```

This test page fails when currently but setting `datachannel.binaryType = "arraybuffer";` in `connect` in `webrtc.mjs` makes it run. I will open a PR for this and then come back to this post.

**Comment by minwidth0px** [comment]
@sinclairzx81 Ok, I read your posts, and I think it's good that you found a way to throw better error messages, which is something that was noticeable before as you wouldn't get any error messages in Firefox when the fetch failed. I haven't had the time to test the new update out yet but I do plan on upgrading soon. 

As for the PR I created above, I don't actually know why "arraybuffer" must be set there, but I tested it and it worked only when that was set there (I'm on 0.8.4 right now). And I don't know why it didn't need to be set for a simple example but does need to be set for the example I gave. However it should be a harmless addition. Maybe you could test that PR against your test suite and see if it makes more requests succeed?

Also, have you looked at https://github.com/webrtc/adapter? I just found it recently. This is a library that abstracts out the differences between browser implementations. It could give some more insight on what exactly the differences are between the browsers in their WebRTC implementations. It's on the official webrtc repo so it should be somewhat accurate.
