### ISSUE TITLE
Tested on Safari yet?

### ISSUE THREAD

**Issue by Cinemacloud** [sinclairzx81/smoke#3]
Very cool project

**Comment by sinclairzx81** [comment]
Hi, thanks.

The specs only currently cover chrome and firefox at this stage, however I'd like to add Safari and the new Edge browser but haven't had a lot of time to look into the project sadly, but do intend to pick it up later in the year.

The tests are implemented with the `karma` framework and the configuration for that is [here](https://github.com/sinclairzx81/smoke/blob/master/packages/smoke-node/test/karma.config.js#L12), I haven't checked for headless Safari, maybe its possible to just add a karma hook for it?

**Comment by Cinemacloud** [comment]
Thanks and can you possibly shed some insight on my other issue raised regarding shell_options not found? If I comment that out it works? but without tracing output.

**Comment by sinclairzx81** [comment]
Will close this off and link to [this](https://github.com/sinclairzx81/smoke/issues/5) issue. Will make of note to review Safari headless browser testing.

Many Thanks !
