### ISSUE TITLE
NodeJS Equivalent

### ISSUE THREAD

**Issue by yovanoc** [sinclairzx81/smoke#6]
Hello, this is a great library!

But can you use something like https://www.npmjs.com/package/isomorphic-ws for allowing this to work on node?

Thanks!

**Comment by sinclairzx81** [comment]
Hi, thanks!

This library is built specifically over WebRTC, so its not really using WebSockets for communication between peers. There is also extra infrastructure required to run things (primarily a signalling infrastructure or hub as mentioned in the readme) so something like isomorphic-ws is unlikely to map over 1-1.

To run smoke in nodejs, id probably look towards something like - https://github.com/node-webrtc/node-webrtc, however smoke is mainly aimed at running web servers inside of web browsers, so some work would be required to port things over to work within a nodejs context.

Hope that helps.
S

**Comment by sinclairzx81** [comment]
Going to close this issue, thanks for the inquiry!
