### ISSUE TITLE
Problem when implementing the pagehub socket example

### ISSUE THREAD

**Issue by bajpai244** [sinclairzx81/smoke#7]
Hello everyone, I am on Ubuntu and I am using firefox. Till this far the REST server example is working fine but when I use the pagehub sockets example I am getting a connection timed out error.

```javascriptimport { Node } from "smoke-node"
const node1 = new Node() // 0.0.0.1
const node2 = new Node() // 0.0.0.2
const node3 = new Node() // 0.0.0.3

node3.sockets.createServer(socket => {
  
  socket.send('hello')

  socket.close()

}).listen(5000)

// connect to node2 from node3 server

const socket = node2.sockets.connect('0.0.0.3', 5000)

socket.on('message', message => {

  console.log(message.data)
})
```

The output of it on the console is 
```
Error: Connection to host '0.0.0.3' timed out.
```

**Comment by sinclairzx81** [comment]
@bajpai244 Hi,

The documentation might be a little out of date with recent hub updates. I've updated the code below for reference. Note you can check the nodes `address` with the following code.

```typescript
node3.address().then(console.log) 
```
Example as follows.
```typescript
import { Node } from 'smoke-node'

const node1 = new Node() // 0.0.0.0
const node2 = new Node() // 1.0.0.0
const node3 = new Node() // 2.0.0.0

node3.sockets.createServer(socket => {
  
  socket.send(`hello from ${socket.local}`)

  socket.close()

}).listen(5000)

// check node3's address...

node3.address().then(console.log) 

const socket = node2.sockets.connect('2.0.0.0', 5000)

socket.on('message', message => {

  console.log(message.data.toString())
})
```
Hope that helps :)
S

**Comment by bajpai244** [comment]
Thanks , so is there any new documentation that you folks are maintaining, because i am thinking of using this thing for a project.

**Comment by sinclairzx81** [comment]
The documentation in the readme should illustrate most of the high level API and it should be more or less up to date. The library is well commented so if you use TypeScript + vscode you should get good info there.

Note, there is only really one developer behind this project, so any contributions to enhance the code, provide examples or enhance the documentation are welcome.

If you're looking to leverage this project, please be mindful this library is still very much in a prototype state and may change into the future. But feel free to fork and experiment.

Good luck!!

**Comment by innerop** [comment]
@sinclairzx81 I'm looking at playing with it too. Love your github handle... good memories.

I am looking forward to contributing if I do end up using it in my project! 

I have high hopes :) ... 

Cheers

**Comment by bajpai244** [comment]
Okay! It is a great project and I will be contributing soon towards it. I know it is not the right place but could share any social media handle so that we could connect and discuss this project.

**Comment by sinclairzx81** [comment]
@bajpai244 I am not really a user of social media, however there is a channel on the freenode IRC network `#smoke` if you wish to discuss technical details there. Any contributions would certainly be welcome :)

Ill close off this issue for the time being.

Cheers
S
